name = "sansnoise"
compatibility_date = "2026-06-03"
main = "worker.js"

[assets]
directory = "./"
not_found_handling = "404-page"
html_handling = "drop-trailing-slash"

[[kv_namespaces]]
binding = "CONTACT_KV"
id = "fba0a009d27d49c8a987bfe143361461"

[vars]
RESEND_API_KEY = ""